
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MSI PC
 */
public class GirisPaneli extends javax.swing.JFrame {

    /**
     * Creates new form Tasarim
     */
    public GirisPaneli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kullanici_adi = new javax.swing.JLabel();
        parola = new javax.swing.JLabel();
        kullanici_adiA = new javax.swing.JTextField();
        parolaA = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş");

        kullanici_adi.setText("Kullanıcı Adı:");

        parola.setText("Parola:");

        jButton1.setText("Giriş Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI PC\\Documents\\GirisPaneli.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(parola))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(kullanici_adi))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(kullanici_adiA, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(parolaA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jButton1))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(parola))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(kullanici_adi))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(kullanici_adiA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(parolaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jButton1))
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String bildirim;
       String kullanıcıA=kullanici_adiA.getText();
      // String parolaA=this.parolaA.getPassword();
      String parolaA=new String(this.parolaA.getPassword());
        if(kullanıcıA.equals("Ali KAHRAMAN")&& parolaA.equals("1234")){
bildirim="Sayın "+kullanıcıA+" sisteme başarılı bir şekilde giriş yaptınız.";

        }
        else if(!kullanıcıA.equals("Ali KAHRAMAN")&&parolaA.equals("1234")){
bildirim="Kullanıcı adı hatalı";
        }
        else if(kullanıcıA.equals("Ali KAHRAMAN")&&!parolaA.equals("1234")){
bildirim="Parola hatalı";
        }
        else {
bildirim="Kullanıcı adı ve parola hatalı";
        }
        if(bildirim.equals("Sayın "+kullanıcıA+" sisteme başarılı bir şekilde giriş yaptınız.")){
            JOptionPane.showMessageDialog(this, bildirim);
                System.exit(0);
        }
        else {
            JOptionPane.showMessageDialog(this,bildirim);
            kullanici_adiA.setText("");
            this.parolaA.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisPaneli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kullanici_adi;
    private javax.swing.JTextField kullanici_adiA;
    private javax.swing.JLabel parola;
    private javax.swing.JPasswordField parolaA;
    // End of variables declaration//GEN-END:variables
}
